apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: argocd-server-hc
  namespace: argocd
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
