backstage:
  image:
    repository: backstage/backstage
    tag: latest
  service:
    type: ClusterIP
    port: 7007
  extraEnvVarsSecrets:
    - backstage-app-secret
  appConfig:
    app:
      title: "Hannes Albeiro Dev Portal"
      baseUrl: "https://backstage.hannesalbeiro.com"
    backend:
      baseUrl: "https://backstage.hannesalbeiro.com"
      database:
        client: pg
        connection:
          host: backstage-postgresql
          port: 5432
          user: postgres
          password: ${POSTGRES_PASSWORD}

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: library/postgres
    tag: 14.22-trixie
  auth:
    database: backstage_plugin_catalog
    existingSecret: "backstage-db-secret"
    secretKeys:
      adminPasswordKey: "postgres-password"
  primary:
    persistence:
      enabled: true
      size: 8Gi
