apiVersion: v2
name: gitea-configs
description: A Helm chart for Gitea configurations
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: gitea
    version: 10.1.3
    repository: https://dl.gitea.com/charts/
