# Config for Gitea Actions (Chart: gitea/actions v0.0.4)
enabled: true

giteaRootURL: ""  # overridden by ArgoCD helm.parameters
existingSecret: "gitea-runner-secret"
existingSecretKey: "token"

statefulset:
  replicas: 1
  serviceAccountName: "gitea-act-runner"
  actRunner:
    config: |
      log:
        level: info
      cache:
        enabled: false
      container:
        require_docker: true
        docker_timeout: 300s
        privileged: true
  dind:
    # GKE Autopilot needs some help with dind
    {}
