provider: google
google:
  project: ""  # overridden by ArgoCD helm.parameters (google.project)
domainFilters: []  # overridden by ArgoCD helm.parameters (domainFilters[0])
sources:
  - service
  - ingress
  - gateway-httproute
policy: sync
registry: txt
txtPrefix: ""
txtOwnerId: "txt2md-cluster"
serviceAccount:
  create: true
  name: "external-dns"
  annotations:
    iam.gke.io/gcp-service-account: ""  # overridden by ArgoCD helm.parameters
