provider: google
google:
  project: {{ .Values.project_id | quote }}
domainFilters:
  - {{ .Values.domain | quote }}
sources:
  - service
  - ingress
  - gateway-httproute
policy: sync
registry: txt
txtOwnerId: "txt2md-cluster"
serviceAccount:
  create: true
  name: "external-dns"
  annotations:
    iam.gke.io/gcp-service-account: "external-dns-gsa@{{ .Values.project_id }}.iam.gserviceaccount.com"
