apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage-cert
  namespace: backstage
spec:
  secretName: backstage-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "backstage.hannesalbeiro.com"
  dnsNames:
  - "backstage.hannesalbeiro.com"
