apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.production.yaml: |
    app:
      title: "Hannes Albeiro Dev Portal"
      baseUrl: https://backstage.hannesalbeiro.com
      signInPage: github

    backend:
      baseUrl: https://backstage.hannesalbeiro.com
      cors:
        origin: https://backstage.hannesalbeiro.com
      database:
        client: pg
        connection:
          host: backstage-postgresql
          port: 5432
          user: postgres
          password: ${POSTGRES_PASSWORD}
      auth:
        dangerouslyDisableDefaultAuthPolicy: false
        keys:
          - secret: "backstage-auth-secret-key"
      reading:
        allow:
          - host: github.com
          - host: raw.githubusercontent.com

    auth:
      environment: production
      providers:
        guest: null
        github:
          production:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            callbackUrl: https://backstage.hannesalbeiro.com/api/auth/github/handler/frame

    signInPage: github

    permission:
      enabled: true

    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}

    catalog:
      locations:
        # Local example entity
        - type: file
          target: /app/local-catalog-info.yaml
        # Hello World Template
        - type: url
          target: https://github.com/joreichhardt/gke-with-toolset/blob/master/backstage-templates/hello-world/template.yaml
          rules:
            - allow: [Template]
        # Import your projects automatically
        - type: url
          target: https://github.com/joreichhardt/txt2md/blob/master/catalog-info.yaml
          rules:
            - allow: [Component, System, API, Group, User, Resource, Location]

  local-catalog-info.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: backstage
      description: The Backstage service itself
    spec:
      type: service
      lifecycle: production
      owner: group:default/admins
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: admins
      description: Administrators of the portal
    spec:
      type: team
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: joreichhardt
    spec:
      profile:
        displayName: joreichhardt
      memberOf: [admins]
