apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.production.yaml: |
    app:
      title: "Hannes Albeiro Dev Portal"
      baseUrl: https://backstage.hannesalbeiro.com

    backend:
      baseUrl: https://backstage.hannesalbeiro.com
      cors:
        origin: https://backstage.hannesalbeiro.com
      database:
        client: pg
        connection:
          host: backstage-postgresql
          port: 5432
          user: postgres
          password: ${POSTGRES_PASSWORD}

    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}

    catalog:
      import:
        entityFilename: catalog-info.yaml
      locations:
        # Import your projects automatically
        - type: url
          target: https://github.com/joreichhardt/txt2md/blob/main/catalog-info.yaml
          rules:
            - allow: [Component, System, API, Group, User, Resource, Location]
