apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.production.yaml: |
    app:
      title: "Hannes Albeiro Dev Portal"
      baseUrl: https://backstage.hannesalbeiro.com

    backend:
      baseUrl: https://backstage.hannesalbeiro.com
      cors:
        origin: https://backstage.hannesalbeiro.com
      database:
        client: pg
        connection:
          host: backstage-postgresql
          port: 5432
          user: postgres
          password: ${POSTGRES_PASSWORD}
      auth:
        dangerouslyDisableDefaultAuthPolicy: true
        keys:
          - secret: "backstage-auth-secret-key"
      reading:
        allow:
          - host: github.com
          - host: raw.githubusercontent.com

    auth:
      environment: production
      allowGuestAccess: false
      providers:
        github:
          production:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}

    signInPage: github

    permission:
      enabled: false

    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}

    catalog:
      locations:
        # Local example entity
        - type: file
          target: /app/local-catalog-info.yaml
        # Import your projects automatically
        - type: url
          target: https://github.com/joreichhardt/txt2md/blob/master/catalog-info.yaml
          rules:
            - allow: [Component, System, API, Group, User, Resource, Location]

  local-catalog-info.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: backstage
      description: The Backstage service itself
    spec:
      type: service
      lifecycle: production
      owner: guest
