apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-postgresql
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-postgresql
  template:
    metadata:
      labels:
        app: backstage-postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:14.22-trixie
        env:
        - name: POSTGRES_DB
          value: backstage_plugin_catalog
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backstage-db-secret
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: backstage-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-postgresql
  namespace: backstage
spec:
  ports:
  - port: 5432
  selector:
    app: backstage-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backstage-db-pvc
  namespace: backstage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
