apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-db-secret
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: backstage-db-secret
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: backstage-db-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-app-secret
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: backstage-app-secret
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: backstage-db-password
  - secretKey: GITHUB_TOKEN
    remoteRef:
      key: github-token
  - secretKey: GITHUB_CLIENT_ID
    remoteRef:
      key: github-client-id
  - secretKey: GITHUB_CLIENT_SECRET
    remoteRef:
      key: github-client-secret
