apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flask-secret-key
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: flask-secret-key
    creationPolicy: Owner
  data:
  - secretKey: flask-secret
    remoteRef:
      key: flask-secret-key
