apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-runner-secret
  namespace: gitea-ci
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: gitea-runner-secret
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: gitea-runner-token
