apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: grafana-admin-secret
    template:
      engineVersion: v2
      data:
        admin-user: "admin"
        admin-password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: grafana-admin-password
