apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-act-runner
  namespace: gitea-ci
  annotations:
    iam.gke.io/gcp-service-account: "gitea-runner-gsa@project-84ddd43d-e408-4cb9-8cb.iam.gserviceaccount.com"
