apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-act-runner
  namespace: gitea-ci
  annotations:
    iam.gke.io/gcp-service-account: "gitea-runner-gsa@{{ .Values.project_id }}.iam.gserviceaccount.com"
